Document: craftos-pc
Title: Debian craftos-pc Manual
Author: <insert document author here>
Abstract: This manual describes what craftos-pc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/craftos-pc/craftos-pc.sgml.gz

Format: postscript
Files: /usr/share/doc/craftos-pc/craftos-pc.ps.gz

Format: text
Files: /usr/share/doc/craftos-pc/craftos-pc.text.gz

Format: HTML
Index: /usr/share/doc/craftos-pc/html/index.html
Files: /usr/share/doc/craftos-pc/html/*.html
