Document: craftos-pc-data
Title: Debian craftos-pc-data Manual
Author: <insert document author here>
Abstract: This manual describes what craftos-pc-data is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/craftos-pc-data/craftos-pc-data.sgml.gz

Format: postscript
Files: /usr/share/doc/craftos-pc-data/craftos-pc-data.ps.gz

Format: text
Files: /usr/share/doc/craftos-pc-data/craftos-pc-data.text.gz

Format: HTML
Index: /usr/share/doc/craftos-pc-data/html/index.html
Files: /usr/share/doc/craftos-pc-data/html/*.html
